#!/usr/bin/perl -w

# Copyright 2008 Ivan Babroŭ (email : ibobrik@gmail.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the license, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

use Archive::Zip qw(:ERROR_CODES);
use Archive::Zip::MemberRead;


my $install_dest = '/opt/AirApps';
my $install_desktop = 0;


sub get_appinfo
{
	my $zip = Archive::Zip->new();
	print "[installer] Getting air application info...\n";
	$zip->read($_[0]) == AZ_OK or die "Can't read air archive: $1\n";
	my $fh = Archive::Zip::MemberRead->new($zip, 'META-INF/AIR/application.xml');
	my $line = '';
	my %hash;
	while (defined($line = $fh->getline()))
	{
		if ($line =~ /<name>(.*)<\/name>/)
		{
			$hash{'name'} = $1;
		} elsif ($line =~ /<description>(.*)<\/description>/)
		{
			$hash{'description'} = $1;
		} elsif ($line =~ /<image(\d{2,3})x\1>(.*)<\/image\1x\1>/)
		{
			push(@{$hash{'icons'}}, $2);
		}
	}
	$fh->close();
	if (!defined($hash{'name'}))
	{
		die "[error] not valid air package!\n";
	}
	return \%hash;
}

sub set_options
{
	while (defined($ARGV[0]) and index($ARGV[0], '-') == 0)
	{
		if ($ARGV[0] eq '-d')
		{
			shift @ARGV;
			$install_dest = shift @ARGV;
		} elsif ($ARGV[0] eq '-f')
		{
			shift @ARGV;
			$install_desktop = 1;
		}
	}
}


set_options();

if (!defined($ARGV[0]))
{
	print "Usage: airinstaller [options] <air_app.air>\n";
	die "Options:\n  -f  install .desktop file\n  -d  installation destination (default: $install_dest)\n";
}

if (!-f $ARGV[0])
{
	die "[error] can't open air package!\n";
}

get_appinfo($ARGV[0]);